#!/bin/bash
# If tune_mm_mlp_adapter is True, all parameters except those of the mm_projector will be frozen (see llava_uhd/train/llava-uhd/train.py #1067)
deepspeed --num_nodes=1 --num_gpus=8 llava_uhd/train/ui_llava/train_mem.py \
    --deepspeed ./scripts/zero2.json \
    --model_name_or_path $llama3_8b \
    --version llama_3 \
    --data_path /data0/jingran/workspace/UI_training_data/LLaVA-Pretrain/blip_laion_cc_sbu_558k.json \
    --image_folder /data0/jingran/workspace/UI_training_data/LLaVA-Pretrain/images \
    --vision_tower openai/clip-vit-large-patch14-336 \
    --mm_projector_type mlp2x_gelu \
    --tune_mm_mlp_adapter True \
    --mm_vision_select_layer -2 \
    --mm_use_im_start_end False \
    --mm_use_im_patch_token False \
    --bf16 True \
    --output_dir ./checkpoints/llava-v1.5-llama3-8b_pretrain \
    --num_train_epochs 1 \
    --per_device_train_batch_size 32 \
    --per_device_eval_batch_size 4 \
    --gradient_accumulation_steps 1 \
    --evaluation_strategy "no" \
    --save_strategy "steps" \
    --save_steps 24000 \
    --save_total_limit 1 \
    --learning_rate 1e-3 \
    --weight_decay 0. \
    --warmup_ratio 0.03 \
    --lr_scheduler_type "cosine" \
    --logging_steps 1 \
    --tf32 True \
    --model_max_length 2048 \
    --gradient_checkpointing True \
    --dataloader_num_workers 4 \
    --lazy_preprocess True \
    --report_to wandb